<<<<<<< HEAD
# Generated by Django 4.2.7 on 2024-03-13 03:27
=======
# Generated by Django 4.2.7 on 2024-01-25 15:30
>>>>>>> 0d6c3cac974086b0c22aab65866da3557ddd972b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
