# Generated by Django 4.2.7 on 2024-04-02 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "equipo_jugador",
            "0002_alter_equipo_usuario_alter_equipo_torneo_usuario_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gol_local", models.IntegerField(default=0)),
                ("gol_visitante", models.IntegerField(default=0)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "equipo_local",
                    models.ManyToManyField(
                        related_name="equipos_locales", to="equipo_jugador.equipo"
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ManyToManyField(
                        related_name="equipos_visitantes", to="equipo_jugador.equipo"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default=users.models.UserManager.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
