<<<<<<< HEAD
# Generated by Django 4.2.7 on 2024-03-13 03:28

from django.db import migrations, models
=======
# Generated by Django 4.2.7 on 2024-01-25 15:31

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 0d6c3cac974086b0c22aab65866da3557ddd972b


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo_jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('detalles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 0d6c3cac974086b0c22aab65866da3557ddd972b
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_local', models.IntegerField(default=0)),
                ('gol_visitante', models.IntegerField(default=0)),
<<<<<<< HEAD
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipo_local', models.ManyToManyField(related_name='equipos_locales', to='equipo_jugador.equipo')),
                ('equipo_visitante', models.ManyToManyField(related_name='equipos_visitantes', to='equipo_jugador.equipo')),
=======
                ('detalle', models.TextField()),
                ('equipo_local', models.ManyToManyField(related_name='equipos_locales', to='equipo_jugador.equipo')),
                ('equipo_visitante', models.ManyToManyField(related_name='equipos_visitantes', to='equipo_jugador.equipo')),
                ('horario_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidos_horario.horario')),
>>>>>>> 0d6c3cac974086b0c22aab65866da3557ddd972b
            ],
        ),
    ]
