# Generated by Django 4.2.7 on 2024-03-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo_jugador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gol_local', models.IntegerField(default=0)),
                ('gol_visitante', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipo_local', models.ManyToManyField(related_name='equipos_locales', to='equipo_jugador.equipo')),
                ('equipo_visitante', models.ManyToManyField(related_name='equipos_visitantes', to='equipo_jugador.equipo')),
            ],
        ),
    ]
