# Generated by Django 4.2.7 on 2024-04-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partidos_horario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partido",
            name="usuario",
            field=models.ForeignKey(
                default=users.models.UserManager.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
