# Generated by Django 4.2.7 on 2024-04-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("torneos", "0002_alter_torneo_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="equipo_jugador/media/equipo"
                    ),
                ),
                ("detalles", models.TextField()),
                (
                    "torneo_equipo",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="torneos.torneo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default=users.models.UserManager.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                ("id_jugador", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("numero_ficha", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "jugador_equipo",
                    models.ManyToManyField(
                        related_name="jugadores", to="equipo_jugador.equipo"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default=users.models.UserManager.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipo_torneo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipo_jugador.equipo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        default=users.models.UserManager.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
